### ISSUE TITLE
Does not support the Urdu scripts?

### ISSUE THREAD

**Issue by miradel51** [isi-nlp/uroman#1]
Hi,

I guess this code does not support the Urdu scripts right?

I could not find the Urdu languages among the identifying input list , so this version does not support the Urdu scripts?

Is there any different version that can convert the Urdu script into the Roman script?

Thanks.

**Comment by thammegowda** [comment]
@miradel51 Yes it does! See it youtself here https://www.isi.edu/~ulf/uroman.html
