### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by flyingleafe** [isi-nlp/uroman#11]
I made a Python wrapper for this software, which basically runs `perl uroman.pl` internally (https://github.com/flyingleafe/uroman-python). The main motivation is to simplify the Python workflows which use `uroman` as a subroutine, mainly multilingual forced alignment using MMS model (https://pytorch.org/audio/2.1.0/tutorials/forced_alignment_for_multilingual_data_tutorial.html?highlight=forced+alignment)

Hope that helps someone.

**Comment by ryderwishart** [comment]
Awesome!

**Comment by uhermjakob** [comment]
Thanks. Responding to growing interest in a Python version, I reimplemented uroman in Python and made it available on PyPI so that people can install it more easily ("pip install uroman").
